<?php
/************************************************************************
  © 2013,2014, 2015 Freestyle Solutions.   All rights reserved.
  FREESTYLE SOLUTIONS, DYDACOMP, FREESTYLE COMMERCE, and all related logos 
  and designs are trademarks of Freestyle Solutions (formerly known as Dydacomp)
  or its affiliates.
  All other product and company names mentioned herein are used for
  identification purposes only, and may be trademarks of
  their respective companies.
 ************************************************************************/

class Freestyle_Advancedexport_Block_Adminhtml_Form_Edit_Tab_General
    extends Mage_Adminhtml_Block_Widget_Form
{

    public function getLastExportData()
    {
        $data = Mage::getModel('advancedexport/history')->getLastExportData();
        if ($data->getCreatedFiles()) {
            $data->setCreatedFiles(unserialize($data->getCreatedFiles()));
        } else {
            $data->setCreatedFiles(array());
        }
        return $data;
    }

    public function getIsPassiveEnabled()
    {
        $passiveEnabled = Mage::getModel('advancedexport/passivemode')
                ->getCollection()
                ->addFieldToFilter('passivemod_enabled', array('eq' => '1'));
        if ($passiveEnabled->count()) {
            return true;
        }
        return false;
    }

    protected function _prepareForm()
    {
        $form = new Varien_Data_Form();
        $this->setForm($form);
        $fieldset = $form->addFieldset(
            'exportparams_form',
            array('legend' => Mage::helper('advancedexport')
            ->__('Create Export Process'))
        );

        $fieldset->addField(
            'export_entity', 'select', array(
            'label'     => Mage::helper('advancedexport')
                        ->__('Entity To Export'),
            'class'     => 'required-entry',
            'required'  => true,
            'name'      => 'export_entity',
            'values'    => array(
                    '' => '', 
                    'customergroup' => 'Customer Groups', 
                    'customer' => 'Customers', 
                    'product' => 'Products', 
                    'category' => 'Categories', 
                    'order' => 'Orders'
                ),
            )
        );
        
        $fieldset->addField(
            'batch_size', 'text', array(
            'label'     => Mage::helper('advancedexport')->__('Batch size'),
            'class'     => 'required-entry',
            'required'  => true,
            'name'      => 'batch_size',
            'value'     => '1000',
            'class'     => 'validate-digits',
            )
        );

        $fieldset->addField(
            'website_id', 'select', array(
            'label'     => Mage::helper('advancedexport')->__('Website ID'),
            'class'     => 'required-entry',
            'required'  => true,
            'name'      => 'website_id',
            'values'    => Mage::getModel('advancedexport/website')
                        ->toOptionArray()
            )
        );
        
        $fieldset->addField(
            'date_start', 
            'date', array(
            'label' => Mage::helper('advancedexport')->__('Start Date'),
            //'after_element_html' => '<small>Comments</small>',
            'image'     => $this->getSkinUrl('images/grid-cal.gif'),
            'name'      => 'date_start',
            'format'    => Mage::app()->getLocale()
                ->getDateFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT),
            'class'     => 'validate-date'
            )
        );

        $fieldset->addField(
            'date_end', 
            'date', array(
            'label'     => Mage::helper('advancedexport')->__('End Date'),
            //'after_element_html' => '<small>Comments</small>',
            'image'     => $this->getSkinUrl('images/grid-cal.gif'),
            'name'      => 'date_end',
            'format'    => Mage::app()->getLocale()
                ->getDateFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT),
            //'format' => 'M/d/y',
            'class'     => 'validate-date'
            )
        );

        $fieldset->addField(
            'ids_to_export', 'text', array(
            'label'     => Mage::helper('advancedexport')
                ->__('Enter ID\'s Separated By Comma'),
            'name'      => 'ids_to_export',
            'after_element_html' => '<small><br>If both "Enter Dates" and '
            . '"Entity IDs" are entered, files will be '
            . 'generated by IDs</small>',
            )
        );

        $this->setTemplate('advancedexport/export_tab_content.phtml');

        $sessionData = Mage::getSingleton('adminhtml/session')
                     ->getData('advancedExportValues');
        //print_r($sessionData);
        $hasDate = isset($sessionData['date_start'])
                && isset($sessionData['date_end']);
        if ($hasDate) {
            $sessionData['date_start'] = strtotime($sessionData['date_start']);
            $sessionData['date_end'] = strtotime($sessionData['date_end']);
        }
        $form->setValues($sessionData);

        return parent::_prepareForm();
    }

    public function getDeleteUrl()
    {
        return $this->getUrl('*/*/deleteexportfiles');
    }
}
